server:
  port: 8080
  servlet:
    context-path: /
  ip: localhost

# Spring相关配置
spring:
  application:
    name: lock
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 20MB # 单个文件最大值
      max-request-size: 100MB # 单个请求文件总计最大值
  redis:
    lettuce: #这里标明使用lettuce配置
      pool:
        max-active: 8   #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms  #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8     #连接池中的最大空闲连接
        min-idle: 0     #连接池中的最小空闲连接
    host: localhost
    port: 6379
    password: 41872410A6EB55CCF34575BC8B317FE0
    database: 0
    redisson:
      config: classpath:redisson-single.yml

# 日志配置
logging:
  config: classpath:log4j2-spring.xml

# knife4j相关配置
knife4j:
  swagger: # swagger相关配置
    enable: true
    base-package: per.jaceding.lock.controller
    contact-email: 931977674@qq.com
    contact-name: jaceding
    contact-url:
    description: ${spring.application.name} API Documents
    title: ${spring.application.name} API Documents
    url: http://${server.ip}:${server.port}${server.servlet.context-path}doc.html
    version: v1
    parameter-config:
      - name: Authorization
        description:
        type: header
        data-type: String
        required: false
        default-value:

  production: false # 是否生产环境，生产环境会关闭swagger和knife4j
  basic:
    enable: true
    username: admin
    password: admin

