server:
  port: 8092
  ip: 127.0.0.1
  servlet:
    context-path: /

# Spring相关配置
spring:
  aop:
    proxy-target-class: false # 启动JDK动态代理
  application:
    name: demo-web
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 2000MB # 单个文件最大值
      max-request-size: 2000MB # 单个请求文件总计最大值
  datasource:
    url: jdbc:mysql://10.69.8.13:3309/weather?useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: kC95aPV3DZOwzT1u
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 10 # 初始化连接池大小
      min-idle: 5 # 最少空闲连接数
      max-active: 20 # 最大连接数
      max-wait: 60000 # 获取连接等待超时的时间
      time-between-eviction-runs-millis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 300000 # 配置一个连接在池中最小生存的时间，单位是毫秒
      validation-query: SELECT 'x' # 测试连接
      filters: slf4j # 通过别名的方式配置扩展插件
      filter:
        slf4j: # 日志配置
          enabled: true
          statement-create-after-log-enabled: false
          statement-close-after-log-enabled: false
          result-set-open-after-log-enabled: false
          result-set-close-after-log-enabled: false
  redis:
    cluster:
      nodes:
        - 10.69.8.12:6380
        - 10.69.8.12:6381
        - 10.69.8.12:6382
        - 10.69.8.13:6380
        - 10.69.8.13:6381
        - 10.69.8.13:6382
        - 10.69.8.14:6380
        - 10.69.8.14:6381
        - 10.69.8.14:6382
      max-redirects: 3
    password: d3l1aGpzZGhrYQ
    database: 0
    lettuce: #这里标明使用lettuce配置
      pool:
        max-active: 8   #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms  #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8     #连接池中的最大空闲连接
        min-idle: 0     #连接池中的最小空闲连接

# mybatis-plus相关配置
mybatis-plus:
  mapper-locations: classpath:/mapperxml/**.xml # mapper xml映射路径
  check-config-location: true # 启动时是否检查MyBatis XML文件是否存在
  type-aliases-package: ${system.base-package}.entity
  configuration:
    map-underscore-to-camel-case: true # 配置mybatis自动将数据库下划线映射成驼峰
    call-setters-on-nulls: true  # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    local-cacheScope: statement # 关闭一级缓存
    cache-enabled: false # 关闭二级缓存
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 控制台打印SQL
  global-config:
    db-config:
      id-type: auto # 全局默认主键类型
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

# 日志配置
logging:
  config: classpath:log4j2.xml

# knife4j相关配置
knife4j:
  enable: true
  swagger: # swagger相关配置
    base-package: ${system.base-package}.controller
    contact-email: 931977674@qq.com
    contact-name: jaceding
    contact-url:
    description: ${spring.application.name} API Documents
    title: ${spring.application.name} API Documents
    url: http://${server.ip}:${server.port}${server.servlet.context-path}doc.html
    version: ${system.version}
    parameter-config:
  production: false # 是否生产环境，生产环境会关闭swagger和knife4j
  basic:
    enable: true
    username: admin
    password: admin

# 系统相关配置
system:
  base-package: per.jaceding.demo
  version: v1
  web-log:
    enable: true
  nowapi: # 第三方api接口：https://www.nowapi.com/
    appkey: 51668
    sign: f1f709efef44942af87a407803066d9b
